/**
 * Linux Executor
 * 
 * Handles SSH installation, configuration, and service management on Linux.
 */

const path = require('path');
const { spawnAsync, execSudo } = require('../../adapters/process');
const { writeFile, ensureDir } = require('../../adapters/fs');
const { ProcessError } = require('../../utils/errors');

/**
 * Install OpenSSH Server on Linux
 * 
 * @param {Object} config - Configuration
 * @param {Logger} logger - Logger instance
 */
async function installSSH(config, logger) {
  try {
    // Update package list
    logger.debug('Updating package list...');
    await execSudo(['apt-get', 'update', '-y'], logger);

    // Install openssh-server
    logger.debug('Installing openssh-server...');
    await execSudo(['apt-get', 'install', '-y', 'openssh-server'], logger);

    logger.debug('OpenSSH Server installed successfully');
  } catch (error) {
    throw new ProcessError(`Failed to install OpenSSH Server: ${error.message}`);
  }
}

/**
 * Configure SSH Server on Linux
 * 
 * @param {Object} config - Configuration
 * @param {Logger} logger - Logger instance
 */
async function configureSSH(config, logger) {
  const sshdConfigPath = '/etc/ssh/sshd_config';

  try {
    // Generate sshd_config content
    const sshdConfig = generateSSHDConfig(config);

    // Write config file (requires sudo)
    logger.debug(`Writing sshd_config to ${sshdConfigPath}...`);
    
    // Write to temp file first
    const tempConfigPath = path.join(config.cwd, '.runner-data', 'tmp', 'sshd_config');
    await ensureDir(path.dirname(tempConfigPath));
    await writeFile(tempConfigPath, sshdConfig);

    // Copy to /etc/ssh/ with sudo
    await execSudo(['cp', tempConfigPath, sshdConfigPath], logger);

    // Set proper permissions
    await execSudo(['chmod', '644', sshdConfigPath], logger);

    // Ensure runtime directory exists for privilege separation
    logger.debug('Ensuring /run/sshd exists...');
    await execSudo(['mkdir', '-p', '/run/sshd'], logger);
    await execSudo(['chmod', '755', '/run/sshd'], logger);

    // Ensure host keys exist
    logger.debug('Ensuring SSH host keys exist...');
    await execSudo(['ssh-keygen', '-A'], logger);

    // Test configuration
    logger.debug('Testing sshd configuration...');
    await execSudo(['sshd', '-t'], logger);

    logger.debug('SSH configuration applied successfully');
  } catch (error) {
    throw new ProcessError(`Failed to configure SSH: ${error.message}`);
  }
}

/**
 * Start SSH service on Linux
 * 
 * @param {Object} config - Configuration
 * @param {Logger} logger - Logger instance
 */
async function startSSH(config, logger) {
  try {
    // Enable SSH service to start on boot
    logger.debug('Enabling SSH service...');
    await execSudo(['systemctl', 'enable', 'ssh'], logger);

    // Restart SSH service
    logger.debug('Restarting SSH service...');
    await execSudo(['systemctl', 'restart', 'ssh'], logger);

    // Check service status
    logger.debug('Checking SSH service status...');
    try {
      await execSudo(['systemctl', 'is-active', 'ssh'], logger);
      logger.debug('SSH service is active');
    } catch (err) {
      // Try 'sshd' instead of 'ssh'
      await execSudo(['systemctl', 'restart', 'sshd'], logger);
      await execSudo(['systemctl', 'is-active', 'sshd'], logger);
      logger.debug('SSH service (sshd) is active');
    }

  } catch (error) {
    throw new ProcessError(`Failed to start SSH service: ${error.message}`);
  }
}

/**
 * Generate sshd_config content
 * 
 * @param {Object} config - Configuration
 * @returns {string} sshd_config content
 */
function generateSSHDConfig(config) {
  const allowUsersArr = config.allowUsers.split(' ').filter(u => u.trim());
  const forceCommandLine = !config.disableForceCwd 
    ? `ForceCommand cd ${config.defaultCwd} && exec $SHELL -l`
    : '';

  return `# SSH Server Configuration - Generated by runner-add-ssh
# Port
Port ${config.port}

# Authentication
PubkeyAuthentication yes
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes

# Security
PermitRootLogin ${config.mode === 'root' ? 'prohibit-password' : 'no'}
StrictModes yes
MaxAuthTries 3
MaxSessions 10

# Allowed users
AllowUsers ${allowUsersArr.join(' ')}

# Subsystems
Subsystem sftp /usr/lib/openssh/sftp-server

# Logging
SyslogFacility AUTH
LogLevel INFO

# Default working directory
${forceCommandLine}

# Performance
UseDNS no
`;
}

module.exports = {
  installSSH,
  configureSSH,
  startSSH
};
